"""Crystal Architect — Generates architecture.md for your project.

This file lives in your repo and tells every AI tool your project's rules.
It survives session resets, platform switches, and context limits.
"""

from pathlib import Path
from crystal_guard.config import load_config, get_crystal_dir, walk_project_files, CODE_EXTENSIONS, is_test_file
from crystal_guard.detector import detect_stack
from crystal_guard.rules.loader import load_rules
from datetime import datetime, timezone


def generate_architecture_md(project_path: str) -> str:
    """Generate architecture.md content from project state and rules."""
    root = Path(project_path).resolve()
    config = load_config(project_path)
    detected = detect_stack(project_path)
    rules = load_rules(project_path, config.stack)

    all_files = walk_project_files(project_path, CODE_EXTENSIONS)
    test_files = [f for f in all_files if is_test_file(f, root)]

    # Map file tree (top 2 levels)
    dirs = set()
    for f in all_files:
        try:
            rel = f.relative_to(root)
            if len(rel.parts) >= 2:
                dirs.add(str(Path(rel.parts[0]) / rel.parts[1]))
            elif len(rel.parts) == 1:
                dirs.add(rel.parts[0])
        except ValueError:
            pass

    lines = []
    lines.append(f"# {config.project_name or root.name} — Architecture Rules")
    lines.append("")
    lines.append("> Auto-generated by Crystal. Every AI tool should read this file before making changes.")
    lines.append(f"> Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}")
    lines.append("")

    # Stack info
    lines.append("## Tech Stack")
    lines.append(f"- **Stack**: {detected['stack_id']}")
    if detected["frontend"]:
        lines.append(f"- **Frontend**: {detected['frontend']}")
    if detected["backend"]:
        lines.append(f"- **Backend**: {detected['backend']}")
    if detected["database"]:
        lines.append(f"- **Database**: {detected['database']}")
    lines.append(f"- **Files**: {len(all_files)} | **Tests**: {len(test_files)}")
    lines.append("")

    # Project structure
    lines.append("## Project Structure")
    lines.append("```")
    for d in sorted(dirs)[:30]:
        lines.append(f"  {d}")
    lines.append("```")
    lines.append("")

    # Architecture rules
    lines.append("## Rules — DO NOT VIOLATE")
    lines.append("")

    arch_rules = rules.get("architecture", {})

    # Frontend rules
    if detected.get("frontend"):
        lines.append("### Frontend")
        frontend_root = arch_rules.get("frontend", {}).get("root", "frontend/src")
        lines.append(f"- All frontend code lives in `{frontend_root}/`")
        lines.append("- **DO NOT** put database queries, filesystem access, or server-side logic in frontend files")
        lines.append("- **DO NOT** use environment variables without the `REACT_APP_` prefix (or `NEXT_PUBLIC_` for Next.js)")
        lines.append("- **DO NOT** put password hashing, JWT signing, or crypto operations in frontend")
        lines.append("- **DO** use API calls (fetch/axios) to communicate with the backend")
        lines.append("")

    # Backend rules
    if detected.get("backend"):
        lines.append("### Backend")
        backend_root = arch_rules.get("backend", {}).get("root", "backend")
        lines.append(f"- All backend code lives in `{backend_root}/`")
        lines.append("- Route files handle HTTP requests only — delegate business logic to service files")
        lines.append("- Model files define data structures only — no business logic, no HTTP handling")
        lines.append("- **DO NOT** put React/Vue/Angular code in backend files")
        lines.append("")

    # Security rules
    lines.append("### Security — CRITICAL")
    lines.append("- **NEVER** hardcode API keys, passwords, or secrets in code")
    lines.append("- **ALWAYS** use environment variables for sensitive values")
    lines.append("- **ALWAYS** add `.env` to `.gitignore`")
    lines.append("- **NEVER** use CORS wildcard (`*`) in production")
    lines.append("- **NEVER** build SQL queries with string concatenation — use parameterized queries")
    lines.append("")

    # Code hygiene
    lines.append("### Code Hygiene")
    lines.append("- Remove all `TODO` and `FIXME` comments before deploying")
    lines.append("- Remove all `console.log` and `print()` debug statements before deploying")
    lines.append("- Replace all placeholder values (`example.com`, `test@test.com`) with real values")
    lines.append("- Do not hardcode `localhost` URLs — use environment variables")
    lines.append("")

    # Session instructions
    lines.append("## Session Instructions")
    lines.append("1. **Read this file** before making any changes")
    lines.append("2. **Do not rewrite** files that are already working — modify only what's needed")
    lines.append("3. **Run `crystal check`** after making changes to verify no rules were broken")
    lines.append("4. **Update `.crystal/prd.md`** with what you built or changed")
    lines.append("5. **Run `crystal handoff`** at the end of the session to create context for next time")
    lines.append("")

    # Custom rules from config
    if config.custom_rules:
        lines.append("## Custom Rules")
        for rule in config.custom_rules:
            lines.append(f"- **{rule.get('name', rule.get('id', 'custom'))}**: {rule.get('message', '')}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Crystal v0.1.0 — https://crystalcodes.dev*")

    return "\n".join(lines)
